### ISSUE TITLE
Add a check-out task

### ISSUE THREAD

**Issue by Scott-Pearce** [jessehouwing/vsts-tfvc-tasks#36] opened 2016-11-22 21:39 UTC
I've found that some files that are part of a project (i.e. a Microsoft Access database) are read-only until explicitly checked-out. Therefore any build time editing of such files will fail. An explicit check out task would solve this issue.

**Comment by jessehouwing** [comment] 2016-11-22 23:45
Can you send me a sample file for me to check this against? In local
workspaces this really shouldn't be needed...

On Nov 22, 2016 21:39, "Scott-Pearce" <notifications@github.com> wrote:

I've found that some files that are part of a project (i.e. a Microsoft
Access database) are read-only until explicitly checked-out. Therefore any
build time editing of such files will fail. An explicit check out task
would solve this issue.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jessehouwing/vsts-tfvc-tasks/issues/36>, or mute the
thread

**Comment by jessehouwing** [comment] 2016-11-29 18:47
I can't reproduce this locally. Can you share:

 * TFS version
 * Build agent version
 * Task version

**Comment by jessehouwing** [comment] 2016-11-30 11:35
I just ran a build with these files and it works flawlessly. This access database got checked in just fine. 
![image](https://cloud.githubusercontent.com/assets/4173387/20750805/eff9114a-b6f8-11e6-87b2-f971c5ea38d7.png)

Your files aren't supposed to be read-only, that's a Server workspace thing and the build agent always uses a local workspace. If you are using server workspaces for whatever reason, or are changing the workspace type as part of the build, then you will get in trouble with my tasks. They rely on local workspaces and edits are detected automatically.

**Comment by jessehouwing** [comment] 2016-11-30 16:05
Looks like you may be running into the same issue as @ChristophLindemann in #37. I can't repro it locally in VSTS, TFS 2015 update 3 and TFS 2017...

**Comment by jessehouwing** [comment] 2016-12-01 09:30
Got verification from Microsoft that your workspace should not be configured as a server workspace and that the build agent doesn't create workspaces with that configuration by itself (or that would be a bug). There has been a very early 2.0 preview agent where the workspaces were created as server and that has subsequently been turned off. It's probably best to change the workspace type to local or remove the workspace altogether so the agent will recreate it.
I will look at building in detection and a warning when the workspace has been configured incorrectly.

**Comment by jessehouwing** [comment] 2016-12-01 14:01
Found the cause for the behavior you're seeing. When using agent version 1.x and using default server workspaces and not allowing multiple checkouts on a project, the build agent will create a server workspace.

Please upgrade to agent 2.x or enable multiple checkouts on your project. 

See #38 for more information.

**Comment by jessehouwing** [comment] 2016-12-03 14:04
after Microsoft came back with the fact that on agent 1.x it is supported to use server workspaces, but that even they didn't realize it ;), I've created an experimental package that holds a Checkout task... if you're willing to help me test and find the cases that are and aren't working, I'd be willing to share it to your accounts.

**Comment by ChristophLindemann** [comment] 2016-12-05 09:15
Hi @jessehouwing,

That sounds awesome, and I am happy to test it here, on TFS 2015.3, and if that works on the produktion server running 2015.2.1.

**Closed** 2017-01-14 15:40 UTC
